version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: rs_postgres
    environment:
      - POSTGRES_DB=roster_sniper
      - POSTGRES_USER=roster_sniper
      - POSTGRES_PASSWORD=TEMP
    volumes:
      - rs_postgres:/var/lib/postgresql/data/

  django:
    image: rs_django
    container_name: rs_django
    volumes:
      - rs_logs:/logs
      - rs_static:/app/django_project/static
    depends_on:
      - postgres

  nginx:
    image: rs_nginx
    container_name: rs_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rs_logs:/logs
      - rs_static:/static
      - rs_letsencrypt:/etc/letsencrypt
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    command: --version
    volumes:
      - rs_letsencrypt:/etc/letsencrypt

volumes:
  rs_logs:
  rs_postgres_data:
  rs_static:
  rs_letsencrypt:
